default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: clapper_dev

test:
  <<: *default
  database: clapper_test

production:
  <<: *default
  database: clapper_prod
